"""
app/data/beaches.py

Curated list of ~50 famous beaches worldwide.
Each beach has a slug (URL), name, location, lat/lon for SST lookup.
"""

BEACHES = [
    # Mediterranean
    {
        "slug": "barcelona-barceloneta",
        "name": "Barceloneta Beach",
        "city": "Barcelona",
        "country": "Spain",
        "lat": 41.378,
        "lon": 2.194,
    },
    {
        "slug": "nice-promenade",
        "name": "Promenade des Anglais",
        "city": "Nice",
        "country": "France",
        "lat": 43.695,
        "lon": 7.266,
    },
    {
        "slug": "mykonos-super-paradise",
        "name": "Super Paradise Beach",
        "city": "Mykonos",
        "country": "Greece",
        "lat": 37.394,
        "lon": 25.361,
    },
    {
        "slug": "santorini-perissa",
        "name": "Perissa Beach",
        "city": "Santorini",
        "country": "Greece",
        "lat": 36.352,
        "lon": 25.479,
    },
    {
        "slug": "amalfi-coast",
        "name": "Amalfi Coast Beach",
        "city": "Amalfi",
        "country": "Italy",
        "lat": 40.634,
        "lon": 14.602,
    },
    {
        "slug": "dubrovnik-banje",
        "name": "Banje Beach",
        "city": "Dubrovnik",
        "country": "Croatia",
        "lat": 42.648,
        "lon": 18.122,
    },
    {
        "slug": "tenerife-las-teresitas",
        "name": "Las Teresitas",
        "city": "Tenerife",
        "country": "Spain",
        "lat": 28.514,
        "lon": -16.186,
    },
    {
        "slug": "mallorca-es-trenc",
        "name": "Es Trenc",
        "city": "Mallorca",
        "country": "Spain",
        "lat": 39.347,
        "lon": 2.987,
    },
    {
        "slug": "ibiza-ses-salines",
        "name": "Ses Salines",
        "city": "Ibiza",
        "country": "Spain",
        "lat": 38.872,
        "lon": 1.412,
    },
    {
        "slug": "positano-beach",
        "name": "Positano Beach",
        "city": "Positano",
        "country": "Italy",
        "lat": 40.628,
        "lon": 14.485,
    },
    {
        "slug": "corfu-paleokastritsa",
        "name": "Paleokastritsa",
        "city": "Corfu",
        "country": "Greece",
        "lat": 39.659,
        "lon": 19.714,
    },
    {
        "slug": "malta-golden-bay",
        "name": "Golden Bay",
        "city": "Malta",
        "country": "Malta",
        "lat": 35.920,
        "lon": 14.338,
    },
    # Atlantic Europe
    {
        "slug": "algarve-praia-da-marinha",
        "name": "Praia da Marinha",
        "city": "Algarve",
        "country": "Portugal",
        "lat": 37.090,
        "lon": -8.407,
    },
    {
        "slug": "lisbon-cascais",
        "name": "Cascais Beach",
        "city": "Cascais",
        "country": "Portugal",
        "lat": 38.697,
        "lon": -9.421,
    },
    {
        "slug": "costa-rica-manuel-antonio",
        "name": "Manuel Antonio",
        "city": "Quepos",
        "country": "Costa Rica",
        "lat": 9.389,
        "lon": -84.136,
    },
    # Caribbean
    {
        "slug": "cancun-playa-delfines",
        "name": "Playa Delfines",
        "city": "Cancún",
        "country": "Mexico",
        "lat": 21.022,
        "lon": -86.852,
    },
    {
        "slug": "barbados-crane-beach",
        "name": "Crane Beach",
        "city": "Barbados",
        "country": "Barbados",
        "lat": 13.083,
        "lon": -59.444,
    },
    {
        "slug": "jamaica-seven-mile",
        "name": "Seven Mile Beach",
        "city": "Negril",
        "country": "Jamaica",
        "lat": 18.268,
        "lon": -78.352,
    },
    {
        "slug": "bahamas-pink-sands",
        "name": "Pink Sands Beach",
        "city": "Harbour Island",
        "country": "Bahamas",
        "lat": 25.506,
        "lon": -76.638,
    },
    {
        "slug": "turks-grace-bay",
        "name": "Grace Bay Beach",
        "city": "Providenciales",
        "country": "Turks & Caicos",
        "lat": 21.813,
        "lon": -72.213,
    },
    {
        "slug": "st-lucia-anse-chastanet",
        "name": "Anse Chastanet",
        "city": "Soufrière",
        "country": "St. Lucia",
        "lat": 13.854,
        "lon": -61.073,
    },
    # Southeast Asia
    {
        "slug": "bali-kuta",
        "name": "Kuta Beach",
        "city": "Bali",
        "country": "Indonesia",
        "lat": -8.718,
        "lon": 115.168,
    },
    {
        "slug": "bali-seminyak",
        "name": "Seminyak Beach",
        "city": "Bali",
        "country": "Indonesia",
        "lat": -8.690,
        "lon": 115.155,
    },
    {
        "slug": "koh-samui-chaweng",
        "name": "Chaweng Beach",
        "city": "Koh Samui",
        "country": "Thailand",
        "lat": 9.535,
        "lon": 100.061,
    },
    {
        "slug": "phuket-patong",
        "name": "Patong Beach",
        "city": "Phuket",
        "country": "Thailand",
        "lat": 7.897,
        "lon": 98.296,
    },
    {
        "slug": "phuket-kata",
        "name": "Kata Beach",
        "city": "Phuket",
        "country": "Thailand",
        "lat": 7.820,
        "lon": 98.299,
    },
    {
        "slug": "krabi-railay",
        "name": "Railay Beach",
        "city": "Krabi",
        "country": "Thailand",
        "lat": 8.012,
        "lon": 98.836,
    },
    {
        "slug": "maldives-veligandu",
        "name": "Veligandu Island",
        "city": "Maldives",
        "country": "Maldives",
        "lat": 5.557,
        "lon": 73.423,
    },
    {
        "slug": "langkawi-cenang",
        "name": "Cenang Beach",
        "city": "Langkawi",
        "country": "Malaysia",
        "lat": 6.296,
        "lon": 99.725,
    },
    {
        "slug": "boracay-white-beach",
        "name": "White Beach",
        "city": "Boracay",
        "country": "Philippines",
        "lat": 11.966,
        "lon": 121.924,
    },
    {
        "slug": "el-nido-nacpan",
        "name": "Nacpan Beach",
        "city": "El Nido",
        "country": "Philippines",
        "lat": 11.241,
        "lon": 119.411,
    },
    # Indian Ocean
    {
        "slug": "zanzibar-nungwi",
        "name": "Nungwi Beach",
        "city": "Zanzibar",
        "country": "Tanzania",
        "lat": -5.726,
        "lon": 39.297,
    },
    {
        "slug": "mauritius-belle-mare",
        "name": "Belle Mare Beach",
        "city": "Mauritius",
        "country": "Mauritius",
        "lat": -20.179,
        "lon": 57.776,
    },
    {
        "slug": "seychelles-anse-source",
        "name": "Anse Source d'Argent",
        "city": "La Digue",
        "country": "Seychelles",
        "lat": -4.369,
        "lon": 55.836,
    },
    {
        "slug": "reunion-boucan-canot",
        "name": "Boucan Canot Beach",
        "city": "Réunion",
        "country": "France",
        "lat": -21.052,
        "lon": 55.214,
    },
    # Australia & Pacific
    {
        "slug": "sydney-bondi",
        "name": "Bondi Beach",
        "city": "Sydney",
        "country": "Australia",
        "lat": -33.891,
        "lon": 151.277,
    },
    {
        "slug": "gold-coast-surfers",
        "name": "Surfers Paradise",
        "city": "Gold Coast",
        "country": "Australia",
        "lat": -27.999,
        "lon": 153.431,
    },
    {
        "slug": "whitsundays-whitehaven",
        "name": "Whitehaven Beach",
        "city": "Whitsundays",
        "country": "Australia",
        "lat": -20.276,
        "lon": 149.032,
    },
    {
        "slug": "bora-bora-matira",
        "name": "Matira Beach",
        "city": "Bora Bora",
        "country": "French Polynesia",
        "lat": -16.533,
        "lon": -151.741,
    },
    {
        "slug": "hawaii-waikiki",
        "name": "Waikiki Beach",
        "city": "Honolulu",
        "country": "USA",
        "lat": 21.277,
        "lon": -157.829,
    },
    {
        "slug": "hawaii-lanikai",
        "name": "Lanikai Beach",
        "city": "Kailua",
        "country": "USA",
        "lat": 21.392,
        "lon": -157.718,
    },
    # Americas
    {
        "slug": "rio-copacabana",
        "name": "Copacabana Beach",
        "city": "Rio de Janeiro",
        "country": "Brazil",
        "lat": -22.971,
        "lon": -43.182,
    },
    {
        "slug": "rio-ipanema",
        "name": "Ipanema Beach",
        "city": "Rio de Janeiro",
        "country": "Brazil",
        "lat": -22.985,
        "lon": -43.202,
    },
    {
        "slug": "miami-south-beach",
        "name": "South Beach",
        "city": "Miami",
        "country": "USA",
        "lat": 25.781,
        "lon": -80.130,
    },
    {
        "slug": "tulum-beach",
        "name": "Tulum Beach",
        "city": "Tulum",
        "country": "Mexico",
        "lat": 20.208,
        "lon": -87.465,
    },
    # Middle East
    {
        "slug": "dubai-jumeirah",
        "name": "Jumeirah Beach",
        "city": "Dubai",
        "country": "UAE",
        "lat": 25.187,
        "lon": 55.228,
    },
    {
        "slug": "aqaba-beach",
        "name": "Aqaba Beach",
        "city": "Aqaba",
        "country": "Jordan",
        "lat": 29.516,
        "lon": 35.006,
    },
    # Africa
    {
        "slug": "cape-town-camps-bay",
        "name": "Camps Bay Beach",
        "city": "Cape Town",
        "country": "South Africa",
        "lat": -33.950,
        "lon": 18.376,
    },
    {
        "slug": "diani-beach",
        "name": "Diani Beach",
        "city": "Mombasa",
        "country": "Kenya",
        "lat": -4.318,
        "lon": 39.567,
    },
]

# Build a lookup dict by slug for fast access
BEACHES_BY_SLUG = {b["slug"]: b for b in BEACHES}
